version: '3.4'

services:
  tennischallenge.api:
    image: ${DOCKER_REGISTRY-}tennischallengeapi
    build:
      context: .
      dockerfile: TennisChallenge.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - tennischallenge.db
  tennischallenge.db:
    image: postgres:latest
    container_name: tennischallenge.db
    environment:
        - POSTGRES_DB=TennisDatabase
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=mysecretpassword
    volumes:
        - ./.containers/challenge-db:/var/lib/postgresql/data
    ports:
        - 5432:5432
